apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: #####
  name: nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tecknosap/k8-gitops-kind-demo
    targetRevision: main
    path: helm/nginx
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true