apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globalsend       # rename from nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/tecknosap/k8-gitops-kind-demo
    targetRevision: main
    path: helm/globalsend      # point to the globalsend Helm chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true